---
all:
  vars:
    ansible_connection: ssh
    ansible_user: ec2-user
    ansible_become: true
    ansible_ssh_private_key_file: /home/ec2-user/jenkins2.pem


zookeeper:
  
  hosts:
    ip-172-31-39-93.us-east-2.compute.internal: 
    ip-172-31-9-68.us-east-2.compute.internal:
    ip-172-31-4-219.us-east-2.compute.intern
      

kafka_broker:
 
  hosts:
    ip-172-31-39-93.us-east-2.compute.internal:
    ip-172-31-9-68.us-east-2.compute.internal:
    ip-172-31-4-219.us-east-2.compute.internal:

schema_registry:
  
  hosts:
    ip-172-31-39-93.us-east-2.compute.internal:
      ## For kerberos sasl protocol, EACH host will need these two variables:
      # schema_registry_kerberos_keytab_path: <The path on ansible host to keytab file, eg. /tmp/keytabs/schemaregistry-ip-172-31-34-246.us-east-2.compute.internal
      # schema_registry_kerberos_principal: The principal configured in kdc server ex: schemaregistry/ip-172-31-34-246.us-east-2.compute.internal@REALM.EXAMPLE.COM>

kafka_rest:
 
  hosts:
    ip-172-31-39-93.us-east-2.compute.internal:
      ## For kerberos sasl protocol, EACH host will need these two variables:
      # kafka_rest_kerberos_keytab_path: <The path on ansible host to keytab file, eg. /tmp/keytabs/restproxy-ip-172-31-34-246.us-east-2.compute.internal
      # kafka_rest_kerberos_principal: The principal configured in kdc server ex: restproxy/ip-172-31-34-246.us-east-2.compute.internal@REALM.EXAMPLE.COM>

ksql:
 
  hosts:
    ip-172-31-39-93.us-east-2.compute.internal:
      

kafka_connect:
 
  hosts:
    ip-172-31-39-93.us-east-2.compute.internal:
      ## For kerberos sasl protocol, EACH host will need these two variables:
      # kafka_connect_kerberos_keytab_path: <The path on ansible host to keytab file, eg. /tmp/keytabs/connect-ip-172-31-34-246.us-east-2.compute.internal
      # kafka_connect_kerberos_principal: The principal configured in kdc server ex: connect/ip-172-31-34-246.us-east-2.compute.internal@REALM.EXAMPLE.COM>



control_center:
 
  hosts:
    ip-172-31-39-93.us-east-2.compute.internal:
   
