---
- name: Verify - zookeeper
  hosts: zookeeper
  gather_facts: false
  tasks:
    - shell: grep "Djdk.tls.ephemeralDHKeySize=2048" /etc/systemd/system/confluent-zookeeper.service.d/override.conf
      changed_when: false

- name: Verify - kafka_broker
  hosts: kafka_broker
  gather_facts: false
  tasks:
    - shell: grep "Djdk.tls.ephemeralDHKeySize=2048" /etc/systemd/system/confluent-server.service.d/override.conf
      changed_when: false

- name: Verify - schema_registry
  hosts: schema_registry
  gather_facts: false
  tasks:
    - shell: grep "Djdk.tls.ephemeralDHKeySize=2048" /etc/systemd/system/confluent-schema-registry.service.d/override.conf
      changed_when: false

- name: Verify - kafka_rest
  hosts: kafka_rest
  gather_facts: false
  tasks:
    - shell: grep "Djdk.tls.ephemeralDHKeySize=2048" /etc/systemd/system/confluent-kafka-rest.service.d/override.conf
      changed_when: false

- name: Verify - kafka_connect
  hosts: kafka_connect
  gather_facts: false
  tasks:
    - shell: grep "Djdk.tls.ephemeralDHKeySize=2048" /etc/systemd/system/confluent-kafka-connect.service.d/override.conf
      changed_when: false

- name: Verify - ksql
  hosts: ksql
  gather_facts: false
  tasks:
    - shell: grep "Djdk.tls.ephemeralDHKeySize=2048" /etc/systemd/system/confluent-ksqldb.service.d/override.conf
      changed_when: false

- name: Verify - control_center
  hosts: control_center
  gather_facts: false
  tasks:
    - shell: grep "Djdk.tls.ephemeralDHKeySize=2048" /etc/systemd/system/confluent-control-center.service.d/override.conf
      changed_when: false
