---
- name: Verify - Confluent CLI
  hosts: all
  gather_facts: false
  tasks:
    - name: Check confluent cli is installed
      command: "/usr/local/bin/confluent version"

- name: Verify - zookeeper
  hosts: zookeeper
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/zookeeper.properties
        property: authProvider.x509
        expected_value: org.apache.zookeeper.server.auth.X509AuthenticationProvider

- name: Verify - kafka_broker
  hosts: kafka_broker
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: sasl.enabled.mechanisms
        expected_value: SCRAM-SHA-512

    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: config.providers.securepass.class
        expected_value: io.confluent.kafka.security.config.provider.SecurePassConfigProvider

    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: zookeeper.ssl.keystore.password
        expected_value: ${securepass:/var/ssl/private/kafka-broker-security.properties:server.properties/zookeeper.ssl.keystore.password}

    - import_role:
        name: confluent.test
        tasks_from: check_ownership.yml
      vars:
        file_name: kafka-broker-security.properties
        custom_path: /var/ssl/private/
        group: confluent
        user: cp-kafka

- name: Verify - schema_registry
  hosts: schema_registry
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/schema-registry/schema-registry.properties
        property: kafkastore.security.protocol
        expected_value: SASL_SSL

    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/schema-registry/schema-registry.properties
        property: config.providers.securepass.class
        expected_value: io.confluent.kafka.security.config.provider.SecurePassConfigProvider

    - import_role:
        name: confluent.test
        tasks_from: check_ownership.yml
      vars:
        file_name: schema-registry-security.properties
        custom_path: /var/ssl/private/
        group: confluent
        user: cp-schema-registry
